"""Add camp-specific fields to scheduled evet

Revision ID: 0d381c369dfb
Revises: 5f3f10a08082
Create Date: 2025-05-19 14:58:58.100000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d381c369dfb'
down_revision = '5f3f10a08082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_camp', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_overnight_camp', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('camp_session_identifier', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('camp_session_end_date', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_scheduled_event_camp_session_identifier'), ['camp_session_identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_event_is_camp'), ['is_camp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_event_is_camp'))
        batch_op.drop_index(batch_op.f('ix_scheduled_event_camp_session_identifier'))
        batch_op.drop_column('camp_session_end_date')
        batch_op.drop_column('camp_session_identifier')
        batch_op.drop_column('is_overnight_camp')
        batch_op.drop_column('cost')
        batch_op.drop_column('is_camp')

    # ### end Alembic commands ###
