"""add requires_transportation to Activity Model

Revision ID: 5f3f10a08082
Revises: c43ef700478a
Create Date: 2025-05-19 11:28:19.674921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f3f10a08082'
down_revision = 'c43ef700478a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_transportation', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('requires_transportation')

    # ### end Alembic commands ###
