"""add camp definition fields to Activity model

Revision ID: 7c10f1da79fe
Revises: 0d381c369dfb
Create Date: 2025-05-19 15:17:12.945450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c10f1da79fe'
down_revision = '0d381c369dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_camp_activity', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('default_camp_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('default_is_overnight', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('default_camp_start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('default_camp_end_time', sa.Time(), nullable=True))
        batch_op.create_index(batch_op.f('ix_activity_is_camp_activity'), ['is_camp_activity'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_is_camp_activity'))
        batch_op.drop_column('default_camp_end_time')
        batch_op.drop_column('default_camp_start_time')
        batch_op.drop_column('default_is_overnight')
        batch_op.drop_column('default_camp_cost')
        batch_op.drop_column('is_camp_activity')

    # ### end Alembic commands ###
